plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/rahul/Desktop/FREELANCING/Strapi/react-frontend/build"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/rahul/Desktop/FREELANCING/Strapi"
command = "npm install && npm run build"

[build.environment]
VITE_FIREBASE_API_KEY = ""
VITE_FIREBASE_AUTH_DOMAIN = ""
VITE_FIREBASE_PROJECT_ID = ""
VITE_FIREBASE_STORAGE_BUCKET = ""
VITE_FIREBASE_MESSAGING_SENDER_ID = ""
VITE_FIREBASE_APP_ID = ""
VITE_FIREBASE_MEASUREMENT_ID = ""

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]