version: "3"
build:
  builder: NIXPACKS
deploy:
  startCommand: "cd strapi-backend && npm run start"
  healthcheckPath: "/_health"
  healthcheckTimeout: 100
  restartPolicyType: "ON_FAILURE"
  restartPolicyMaxRetries: 10
